application: vealous
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /god/disqus/?.*
  script: god/disqus.py

- url: /god/twitter/?.*
  script: god/twitter.py

- url: /god/douban/?.*
  script: god/douban.py

- url: /god/?.*
  script: god/main.py

- url: /_ah/xmpp/message/chat/
  script: service/chat.py

- url: /.*
  script: service/blog.py

inbound_services:
- xmpp_message
